name: ldma
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.6+2



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/lang/en.json
    - lib/lang/de.json
    - lib/lang/hi.json
    - lib/img/generell/cocktails.jpg
    - lib/img/generell/gradient_middle.png
    - lib/img/generell/gradient_small.png
    - lib/img/generell/gradient.png
    - lib/img/generell/cocktails.jpg
    - lib/img/alk/43_bear.png
    - lib/img/alk/bacardi_bear.png
    - lib/img/alk/bacardi-razz_bear.png
    - lib/img/alk/belvedere-vodka-2017_bear.png
    - lib/img/alk/captain-morgan_bear.png
    - lib/img/alk/gin_bear.png
    - lib/img/alk/havana-club_bear.png
    - lib/img/alk/jackdaniels_bear.png
    - lib/img/alk/korn_bear.png
    - lib/img/alk/product_page_hero_bottle.png
    - lib/img/alk/tequila_bear.png
    - lib/img/icons/icons8-limonade-50.png
    - lib/img/icons/icons8-waage-50.png
    - lib/img/icons/icons8-whiskey-64.png
    - lib/img/mische/cola_bear.png
    - lib/img/mische/eistee_bear.png
    - lib/img/mische/fanta_bear.png
    - lib/img/mische/lemon.jpg
    - lib/img/mische/milk_bear.png
    - lib/img/mische/OJuice_bear.png
    - lib/img/mische/redbull.png
    - lib/img/mische/sprite_bear.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
